const contentdb = [
		["Zeit", "t", "1 s (Sekunde)"],
		["Masse", "m", "1 kg (Kilogramm)"],
		["Länge, Strecke", "l, s", "1 m (Meter)"],
		["Geschwindigkeit", "v", "1 \\frac{m}{s}"],
		["Druck", "p", "1 \\frac{N}{m^2} = 1 Pa (Pascal)"],
		["Impuls", "\\vec{p}", "\\frac{kg \\cdot m}{s}"],
		["Kraft", "F", "1 N (Newton)"],
		["Dichte", "&rho;", "1 \\frac{kg}{m^3}"],
		["Erd- / Fallbeschleunigung", "g", "9,81\\frac{m}{s^2} = 9,81 \\frac{N}{kg}"],
		["Beschleunigung", "a", "1 \\frac{m}{s^2}"],
		["Energie", "E", "1 J (Joule)"],
		["Leistung, Energiestrom", "P", "1 \\frac{J}{s} = 1 W (Watt)"],
		["thermodynamische Temperatur", "T", "1 K (Kelvin)"],
		["Stromstärke", "I", "1 A (Ampere)"],
		["el. Widerstand", "R", "1 \\Omega (Ohm)"],
		["el. Spannung", "U", "1 V (Volt)"],
		["el. Potential", "&Phi;, &phi;, &#981;", "1 V (Volt)"],
		["el. Ladung", "Q", "1 C (Coulomb)"],
		["Celsius-Temperatur", "&theta;, &#977;", "1 °C (Grad Celsius)"],
		["Frequenz", "f", "\\frac{1}{s} = 1 Hz (Hertz)"],
		["Wellenlänge", "&lambda;", "1 m"],
		["Lichtgeschwindigkeit", "c<sub>0</sub>", "299.792.458 \\frac{m}{s} \\approx 300.000 \\frac{km}{s}"],
		];

